service: "hca-metadata-schema"

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-apigw-binary

custom:
  private: ${file(private.yml)}
  apigwBinary:
    types:
      - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

provider:
  name: aws
  runtime: python3.6
  region: ${self:custom.private.region}
  stage: ${self:custom.private.stage}

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate
          method: post
          cors: true